CREATE TABLE IF NOT EXISTS eth_tx (
  hash VARCHAR PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER eth_tx_updated_at
  BEFORE UPDATE ON eth_tx
  FOR EACH ROW
  EXECUTE PROCEDURE updated_at();
